classdef SetIORequest < robotics.ros.Message
    %SetIORequest MATLAB implementation of ur_msgs/SetIORequest
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'ur_msgs/SetIORequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '144e866c50167f6d4b99948cba355b8c' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant)
        FUNSETDIGITALOUT = int8(1)
        FUNSETFLAG = int8(2)
        FUNSETANALOGOUT = int8(3)
        FUNSETTOOLVOLTAGE = int8(4)
    end
    
    properties (Dependent)
        Fun
        Pin
        State
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Fun', 'Pin', 'State'} % List of non-constant message properties
        ROSPropertyList = {'fun', 'pin', 'state'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = SetIORequest(msg)
            %SetIORequest Construct the message object SetIORequest
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function fun = get.Fun(obj)
            %get.Fun Get the value for property Fun
            fun = int8(obj.JavaMessage.getFun);
        end
        
        function set.Fun(obj, fun)
            %set.Fun Set the value for property Fun
            validateattributes(fun, {'numeric'}, {'nonempty', 'scalar'}, 'SetIORequest', 'Fun');
            
            obj.JavaMessage.setFun(fun);
        end
        
        function pin = get.Pin(obj)
            %get.Pin Get the value for property Pin
            pin = int8(obj.JavaMessage.getPin);
        end
        
        function set.Pin(obj, pin)
            %set.Pin Set the value for property Pin
            validateattributes(pin, {'numeric'}, {'nonempty', 'scalar'}, 'SetIORequest', 'Pin');
            
            obj.JavaMessage.setPin(pin);
        end
        
        function state = get.State(obj)
            %get.State Get the value for property State
            state = single(obj.JavaMessage.getState);
        end
        
        function set.State(obj, state)
            %set.State Set the value for property State
            validateattributes(state, {'numeric'}, {'nonempty', 'scalar'}, 'SetIORequest', 'State');
            
            obj.JavaMessage.setState(state);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Fun = obj.Fun;
            cpObj.Pin = obj.Pin;
            cpObj.State = obj.State;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Fun = strObj.Fun;
            obj.Pin = strObj.Pin;
            obj.State = strObj.State;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Fun = obj.Fun;
            strObj.Pin = obj.Pin;
            strObj.State = obj.State;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.ur_msgs.SetIORequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.ur_msgs.SetIORequest;
            obj.reload(strObj);
        end
    end
end
