#!/usr/bin/env python

import copy
import rospy
from geometry_msgs.msg import Vector3, Pose, Twist, TwistStamped

from rockwalk_ur10_control.UR10Control import MoveitControl
from rockwalk_ur10_control.Subscribers import SubscriberRockwalkKinematics
from rockwalk_ur10_control.RelocationTiming import zigzag_relocation_timing
from rockwalk_ur10_control.MotionTemplates import *


if __name__ == '__main__':
    rospy.init_node("rockwalk_ur10_node", anonymous=True)

    ur10_moveit_control = MoveitControl("manipulator")
    ur10_moveit_control.setup_planning_scene()

    # initialize arm pose:
    initial_pose = initial_robot_pose_1()
    ur10_moveit_control.reach_target_pose(initial_pose)

    rw_kinematics_sub = SubscriberRockwalkKinematics()

    rospy.sleep(5)

    rockwalk_step = 0

    rate = rospy.Rate(50)

    while not rospy.is_shutdown():

        rockwalk_step = zigzag_relocation_timing(rockwalk_step,
                                                 rw_kinematics_sub._body_euler,
                                                 rw_kinematics_sub._body_twist,
                                                 ur10_moveit_control, initial_pose)

        rate.sleep()

    rospy.spin()
