#!/usr/bin/env python

import rospy
from geometry_msgs.msg import Pose, PoseArray, Point, Quaternion

from rockwalk_planner.ZigzagWaypointGenerator import ZigzagWaypoints
from rockwalk_planner.ApexPathServer import ApexPathServer


if __name__ == '__main__':
    rospy.init_node("rockwalk_zigzag_planner_node", anonymous=True)


    zigzag_waypoint_generator = ZigzagWaypoints()
    # zigzag_waypoints_generator.generate_zigzag_waypoints()
    apex_path = zigzag_waypoint_generator.load_zigzag_waypoints()

    print(apex_path)

    apex_path_server = ApexPathServer(apex_path)



    rospy.spin()
