// Generated by gencpp from file ur_msgs/DualArmEff.msg
// DO NOT EDIT!


#ifndef UR_MSGS_MESSAGE_DUALARMEFF_H
#define UR_MSGS_MESSAGE_DUALARMEFF_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace ur_msgs
{
template <class ContainerAllocator>
struct DualArmEff_
{
  typedef DualArmEff_<ContainerAllocator> Type;

  DualArmEff_()
    : HongTargetPose()
    , KongTargetPose()  {
    }
  DualArmEff_(const ContainerAllocator& _alloc)
    : HongTargetPose(_alloc)
    , KongTargetPose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _HongTargetPose_type;
  _HongTargetPose_type HongTargetPose;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _KongTargetPose_type;
  _KongTargetPose_type KongTargetPose;




  typedef boost::shared_ptr< ::ur_msgs::DualArmEff_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur_msgs::DualArmEff_<ContainerAllocator> const> ConstPtr;

}; // struct DualArmEff_

typedef ::ur_msgs::DualArmEff_<std::allocator<void> > DualArmEff;

typedef boost::shared_ptr< ::ur_msgs::DualArmEff > DualArmEffPtr;
typedef boost::shared_ptr< ::ur_msgs::DualArmEff const> DualArmEffConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur_msgs::DualArmEff_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur_msgs::DualArmEff_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ur_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ur_msgs': ['/home/nazir/ws_moveit/src/universal_robot/ur_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ur_msgs::DualArmEff_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur_msgs::DualArmEff_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_msgs::DualArmEff_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_msgs::DualArmEff_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_msgs::DualArmEff_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_msgs::DualArmEff_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur_msgs::DualArmEff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc2cdf957047a17b7bfeba54584a1753";
  }

  static const char* value(const ::ur_msgs::DualArmEff_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc2cdf957047a17bULL;
  static const uint64_t static_value2 = 0x7bfeba54584a1753ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur_msgs::DualArmEff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur_msgs/DualArmEff";
  }

  static const char* value(const ::ur_msgs::DualArmEff_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur_msgs::DualArmEff_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose HongTargetPose\n\
geometry_msgs/Pose KongTargetPose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::ur_msgs::DualArmEff_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur_msgs::DualArmEff_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.HongTargetPose);
      stream.next(m.KongTargetPose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DualArmEff_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur_msgs::DualArmEff_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur_msgs::DualArmEff_<ContainerAllocator>& v)
  {
    s << indent << "HongTargetPose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.HongTargetPose);
    s << indent << "KongTargetPose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.KongTargetPose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR_MSGS_MESSAGE_DUALARMEFF_H
