#!/usr/bin/env python

import rospy

import sys
import select
import tty
import termios


from rockwalk_kinematics.Subscribers import SubscriberKinematicsNode
from rockwalk_kinematics.Visualization import KinematicsVisualization
from rockwalk_kinematics.Publishers import VisualizationPublishers


def isData():
    return select.select([sys.stdin], [], [], 0) == ([sys.stdin], [], [])

old_settings = termios.tcgetattr(sys.stdin)

if __name__ == '__main__':
    rospy.init_node("rockwalk_visualization_node", anonymous=True)


    sub_kinematics = SubscriberKinematicsNode()
    pub_visualization = VisualizationPublishers()
    rospy.sleep(2)

    object_visualization = KinematicsVisualization(pub_visualization, sub_kinematics)


    rate = rospy.Rate(50)


    try:
        tty.setcbreak(sys.stdin.fileno())

        while not rospy.is_shutdown():

            object_visualization.publish_object_marker()
            object_visualization.publish_contact_path_marker()
            object_visualization.publish_apex_position_marker()
            object_visualization.publish_apex_path_marker()
            object_visualization.publish_apex_velocity_marker()
            object_visualization.publish_CoM_marker()
            object_visualization.publish_CoM_path_marker()
            object_visualization.publish_CoM_velocity_marker()
            object_visualization.publish_angular_velocity_marker()
            object_visualization.publish_apex_plane_marker()
            # object_visualization.publish_kong_tcp_velocity_marker()
            object_visualization.publish_next_waypoint_marker()
            object_visualization.publish_next_waypoint_path_marker()
            object_visualization.publish_waypoint_path()

            if isData():
                c = sys.stdin.read(1)

                if c == '\x1b':         # x1b is ESC
                    object_visualization = KinematicsVisualization(pub_visualization, sub_kinematics)


            rate.sleep()
        rospy.spin()

    finally:
        termios.tcsetattr(sys.stdin, termios.TCSADRAIN, old_settings)
