classdef GetCartesianPathResponse < robotics.ros.Message
    %GetCartesianPathResponse MATLAB implementation of moveit_msgs/GetCartesianPathResponse
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'moveit_msgs/GetCartesianPathResponse' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '45414110461a45eb0e273e013924ce59' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        MoveitMsgsMoveItErrorCodesClass = robotics.ros.msg.internal.MessageFactory.getClassForType('moveit_msgs/MoveItErrorCodes') % Dispatch to MATLAB class for message type moveit_msgs/MoveItErrorCodes
        MoveitMsgsRobotStateClass = robotics.ros.msg.internal.MessageFactory.getClassForType('moveit_msgs/RobotState') % Dispatch to MATLAB class for message type moveit_msgs/RobotState
        MoveitMsgsRobotTrajectoryClass = robotics.ros.msg.internal.MessageFactory.getClassForType('moveit_msgs/RobotTrajectory') % Dispatch to MATLAB class for message type moveit_msgs/RobotTrajectory
    end
    
    properties (Dependent)
        StartState
        Solution
        Fraction
        ErrorCode
    end
    
    properties (Access = protected)
        Cache = struct('StartState', [], 'Solution', [], 'ErrorCode', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'ErrorCode', 'Fraction', 'Solution', 'StartState'} % List of non-constant message properties
        ROSPropertyList = {'error_code', 'fraction', 'solution', 'start_state'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = GetCartesianPathResponse(msg)
            %GetCartesianPathResponse Construct the message object GetCartesianPathResponse
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function startstate = get.StartState(obj)
            %get.StartState Get the value for property StartState
            if isempty(obj.Cache.StartState)
                obj.Cache.StartState = feval(obj.MoveitMsgsRobotStateClass, obj.JavaMessage.getStartState);
            end
            startstate = obj.Cache.StartState;
        end
        
        function set.StartState(obj, startstate)
            %set.StartState Set the value for property StartState
            validateattributes(startstate, {obj.MoveitMsgsRobotStateClass}, {'nonempty', 'scalar'}, 'GetCartesianPathResponse', 'StartState');
            
            obj.JavaMessage.setStartState(startstate.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.StartState)
                obj.Cache.StartState.setJavaObject(startstate.getJavaObject);
            end
        end
        
        function solution = get.Solution(obj)
            %get.Solution Get the value for property Solution
            if isempty(obj.Cache.Solution)
                obj.Cache.Solution = feval(obj.MoveitMsgsRobotTrajectoryClass, obj.JavaMessage.getSolution);
            end
            solution = obj.Cache.Solution;
        end
        
        function set.Solution(obj, solution)
            %set.Solution Set the value for property Solution
            validateattributes(solution, {obj.MoveitMsgsRobotTrajectoryClass}, {'nonempty', 'scalar'}, 'GetCartesianPathResponse', 'Solution');
            
            obj.JavaMessage.setSolution(solution.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Solution)
                obj.Cache.Solution.setJavaObject(solution.getJavaObject);
            end
        end
        
        function fraction = get.Fraction(obj)
            %get.Fraction Get the value for property Fraction
            fraction = double(obj.JavaMessage.getFraction);
        end
        
        function set.Fraction(obj, fraction)
            %set.Fraction Set the value for property Fraction
            validateattributes(fraction, {'numeric'}, {'nonempty', 'scalar'}, 'GetCartesianPathResponse', 'Fraction');
            
            obj.JavaMessage.setFraction(fraction);
        end
        
        function errorcode = get.ErrorCode(obj)
            %get.ErrorCode Get the value for property ErrorCode
            if isempty(obj.Cache.ErrorCode)
                obj.Cache.ErrorCode = feval(obj.MoveitMsgsMoveItErrorCodesClass, obj.JavaMessage.getErrorCode);
            end
            errorcode = obj.Cache.ErrorCode;
        end
        
        function set.ErrorCode(obj, errorcode)
            %set.ErrorCode Set the value for property ErrorCode
            validateattributes(errorcode, {obj.MoveitMsgsMoveItErrorCodesClass}, {'nonempty', 'scalar'}, 'GetCartesianPathResponse', 'ErrorCode');
            
            obj.JavaMessage.setErrorCode(errorcode.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.ErrorCode)
                obj.Cache.ErrorCode.setJavaObject(errorcode.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.StartState = [];
            obj.Cache.Solution = [];
            obj.Cache.ErrorCode = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Fraction = obj.Fraction;
            
            % Recursively copy compound properties
            cpObj.StartState = copy(obj.StartState);
            cpObj.Solution = copy(obj.Solution);
            cpObj.ErrorCode = copy(obj.ErrorCode);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Fraction = strObj.Fraction;
            obj.StartState = feval([obj.MoveitMsgsRobotStateClass '.loadobj'], strObj.StartState);
            obj.Solution = feval([obj.MoveitMsgsRobotTrajectoryClass '.loadobj'], strObj.Solution);
            obj.ErrorCode = feval([obj.MoveitMsgsMoveItErrorCodesClass '.loadobj'], strObj.ErrorCode);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Fraction = obj.Fraction;
            strObj.StartState = saveobj(obj.StartState);
            strObj.Solution = saveobj(obj.Solution);
            strObj.ErrorCode = saveobj(obj.ErrorCode);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.moveit_msgs.GetCartesianPathResponse.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.moveit_msgs.GetCartesianPathResponse;
            obj.reload(strObj);
        end
    end
end
