classdef GetStateValidityRequest < robotics.ros.Message
    %GetStateValidityRequest MATLAB implementation of moveit_msgs/GetStateValidityRequest
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'moveit_msgs/GetStateValidityRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'b569c609cafad20ba7d0e46e70e7cab1' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        MoveitMsgsConstraintsClass = robotics.ros.msg.internal.MessageFactory.getClassForType('moveit_msgs/Constraints') % Dispatch to MATLAB class for message type moveit_msgs/Constraints
        MoveitMsgsRobotStateClass = robotics.ros.msg.internal.MessageFactory.getClassForType('moveit_msgs/RobotState') % Dispatch to MATLAB class for message type moveit_msgs/RobotState
    end
    
    properties (Dependent)
        RobotState
        GroupName
        Constraints
    end
    
    properties (Access = protected)
        Cache = struct('RobotState', [], 'Constraints', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Constraints', 'GroupName', 'RobotState'} % List of non-constant message properties
        ROSPropertyList = {'constraints', 'group_name', 'robot_state'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = GetStateValidityRequest(msg)
            %GetStateValidityRequest Construct the message object GetStateValidityRequest
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function robotstate = get.RobotState(obj)
            %get.RobotState Get the value for property RobotState
            if isempty(obj.Cache.RobotState)
                obj.Cache.RobotState = feval(obj.MoveitMsgsRobotStateClass, obj.JavaMessage.getRobotState);
            end
            robotstate = obj.Cache.RobotState;
        end
        
        function set.RobotState(obj, robotstate)
            %set.RobotState Set the value for property RobotState
            validateattributes(robotstate, {obj.MoveitMsgsRobotStateClass}, {'nonempty', 'scalar'}, 'GetStateValidityRequest', 'RobotState');
            
            obj.JavaMessage.setRobotState(robotstate.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.RobotState)
                obj.Cache.RobotState.setJavaObject(robotstate.getJavaObject);
            end
        end
        
        function groupname = get.GroupName(obj)
            %get.GroupName Get the value for property GroupName
            groupname = char(obj.JavaMessage.getGroupName);
        end
        
        function set.GroupName(obj, groupname)
            %set.GroupName Set the value for property GroupName
            validateattributes(groupname, {'char'}, {}, 'GetStateValidityRequest', 'GroupName');
            
            obj.JavaMessage.setGroupName(groupname);
        end
        
        function constraints = get.Constraints(obj)
            %get.Constraints Get the value for property Constraints
            if isempty(obj.Cache.Constraints)
                obj.Cache.Constraints = feval(obj.MoveitMsgsConstraintsClass, obj.JavaMessage.getConstraints);
            end
            constraints = obj.Cache.Constraints;
        end
        
        function set.Constraints(obj, constraints)
            %set.Constraints Set the value for property Constraints
            validateattributes(constraints, {obj.MoveitMsgsConstraintsClass}, {'nonempty', 'scalar'}, 'GetStateValidityRequest', 'Constraints');
            
            obj.JavaMessage.setConstraints(constraints.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Constraints)
                obj.Cache.Constraints.setJavaObject(constraints.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.RobotState = [];
            obj.Cache.Constraints = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.GroupName = obj.GroupName;
            
            % Recursively copy compound properties
            cpObj.RobotState = copy(obj.RobotState);
            cpObj.Constraints = copy(obj.Constraints);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.GroupName = strObj.GroupName;
            obj.RobotState = feval([obj.MoveitMsgsRobotStateClass '.loadobj'], strObj.RobotState);
            obj.Constraints = feval([obj.MoveitMsgsConstraintsClass '.loadobj'], strObj.Constraints);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.GroupName = obj.GroupName;
            strObj.RobotState = saveobj(obj.RobotState);
            strObj.Constraints = saveobj(obj.Constraints);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.moveit_msgs.GetStateValidityRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.moveit_msgs.GetStateValidityRequest;
            obj.reload(strObj);
        end
    end
end
