classdef GraspPlanningResponse < robotics.ros.Message
    %GraspPlanningResponse MATLAB implementation of moveit_msgs/GraspPlanningResponse
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'moveit_msgs/GraspPlanningResponse' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'bb8169d403b6e9f96bf61e22a50d13ae' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        MoveitMsgsGraspClass = robotics.ros.msg.internal.MessageFactory.getClassForType('moveit_msgs/Grasp') % Dispatch to MATLAB class for message type moveit_msgs/Grasp
        MoveitMsgsMoveItErrorCodesClass = robotics.ros.msg.internal.MessageFactory.getClassForType('moveit_msgs/MoveItErrorCodes') % Dispatch to MATLAB class for message type moveit_msgs/MoveItErrorCodes
    end
    
    properties (Dependent)
        ErrorCode
        Grasps
    end
    
    properties (Access = protected)
        Cache = struct('Grasps', [], 'ErrorCode', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'ErrorCode', 'Grasps'} % List of non-constant message properties
        ROSPropertyList = {'error_code', 'grasps'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = GraspPlanningResponse(msg)
            %GraspPlanningResponse Construct the message object GraspPlanningResponse
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function errorcode = get.ErrorCode(obj)
            %get.ErrorCode Get the value for property ErrorCode
            if isempty(obj.Cache.ErrorCode)
                obj.Cache.ErrorCode = feval(obj.MoveitMsgsMoveItErrorCodesClass, obj.JavaMessage.getErrorCode);
            end
            errorcode = obj.Cache.ErrorCode;
        end
        
        function set.ErrorCode(obj, errorcode)
            %set.ErrorCode Set the value for property ErrorCode
            validateattributes(errorcode, {obj.MoveitMsgsMoveItErrorCodesClass}, {'nonempty', 'scalar'}, 'GraspPlanningResponse', 'ErrorCode');
            
            obj.JavaMessage.setErrorCode(errorcode.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.ErrorCode)
                obj.Cache.ErrorCode.setJavaObject(errorcode.getJavaObject);
            end
        end
        
        function grasps = get.Grasps(obj)
            %get.Grasps Get the value for property Grasps
            if isempty(obj.Cache.Grasps)
                javaArray = obj.JavaMessage.getGrasps;
                array = obj.readJavaArray(javaArray, obj.MoveitMsgsGraspClass);
                obj.Cache.Grasps = feval(obj.MoveitMsgsGraspClass, array);
            end
            grasps = obj.Cache.Grasps;
        end
        
        function set.Grasps(obj, grasps)
            %set.Grasps Set the value for property Grasps
            if ~isvector(grasps) && isempty(grasps)
                % Allow empty [] input
                grasps = feval([obj.MoveitMsgsGraspClass '.empty'], 0, 1);
            end
            
            validateattributes(grasps, {obj.MoveitMsgsGraspClass}, {'vector'}, 'GraspPlanningResponse', 'Grasps');
            
            javaArray = obj.JavaMessage.getGrasps;
            array = obj.writeJavaArray(grasps, javaArray, obj.MoveitMsgsGraspClass);
            obj.JavaMessage.setGrasps(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Grasps)
                obj.Cache.Grasps = [];
                obj.Cache.Grasps = obj.Grasps;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Grasps = [];
            obj.Cache.ErrorCode = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.ErrorCode = copy(obj.ErrorCode);
            cpObj.Grasps = copy(obj.Grasps);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.ErrorCode = feval([obj.MoveitMsgsMoveItErrorCodesClass '.loadobj'], strObj.ErrorCode);
            GraspsCell = arrayfun(@(x) feval([obj.MoveitMsgsGraspClass '.loadobj'], x), strObj.Grasps, 'UniformOutput', false);
            obj.Grasps = vertcat(GraspsCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.ErrorCode = saveobj(obj.ErrorCode);
            strObj.Grasps = arrayfun(@(x) saveobj(x), obj.Grasps);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.moveit_msgs.GraspPlanningResponse.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.moveit_msgs.GraspPlanningResponse;
            obj.reload(strObj);
        end
    end
end
