classdef LinkScale < robotics.ros.Message
    %LinkScale MATLAB implementation of moveit_msgs/LinkScale
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'moveit_msgs/LinkScale' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '19faf226446bfb2f645a4da6f2a56166' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        LinkName
        Scale
    end
    
    properties (Constant, Hidden)
        PropertyList = {'LinkName', 'Scale'} % List of non-constant message properties
        ROSPropertyList = {'link_name', 'scale'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = LinkScale(msg)
            %LinkScale Construct the message object LinkScale
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function linkname = get.LinkName(obj)
            %get.LinkName Get the value for property LinkName
            linkname = char(obj.JavaMessage.getLinkName);
        end
        
        function set.LinkName(obj, linkname)
            %set.LinkName Set the value for property LinkName
            validateattributes(linkname, {'char'}, {}, 'LinkScale', 'LinkName');
            
            obj.JavaMessage.setLinkName(linkname);
        end
        
        function scale = get.Scale(obj)
            %get.Scale Get the value for property Scale
            scale = double(obj.JavaMessage.getScale);
        end
        
        function set.Scale(obj, scale)
            %set.Scale Set the value for property Scale
            validateattributes(scale, {'numeric'}, {'nonempty', 'scalar'}, 'LinkScale', 'Scale');
            
            obj.JavaMessage.setScale(scale);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.LinkName = obj.LinkName;
            cpObj.Scale = obj.Scale;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.LinkName = strObj.LinkName;
            obj.Scale = strObj.Scale;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.LinkName = obj.LinkName;
            strObj.Scale = obj.Scale;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.moveit_msgs.LinkScale.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.moveit_msgs.LinkScale;
            obj.reload(strObj);
        end
    end
end
