classdef ObjectColor < robotics.ros.Message
    %ObjectColor MATLAB implementation of moveit_msgs/ObjectColor
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'moveit_msgs/ObjectColor' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'ec3bd6f103430e64b2ae706a67d8488e' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        StdMsgsColorRGBAClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/ColorRGBA') % Dispatch to MATLAB class for message type std_msgs/ColorRGBA
    end
    
    properties (Dependent)
        Id
        Color
    end
    
    properties (Access = protected)
        Cache = struct('Color', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Color', 'Id'} % List of non-constant message properties
        ROSPropertyList = {'color', 'id'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ObjectColor(msg)
            %ObjectColor Construct the message object ObjectColor
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function id = get.Id(obj)
            %get.Id Get the value for property Id
            id = char(obj.JavaMessage.getId);
        end
        
        function set.Id(obj, id)
            %set.Id Set the value for property Id
            validateattributes(id, {'char'}, {}, 'ObjectColor', 'Id');
            
            obj.JavaMessage.setId(id);
        end
        
        function color = get.Color(obj)
            %get.Color Get the value for property Color
            if isempty(obj.Cache.Color)
                obj.Cache.Color = feval(obj.StdMsgsColorRGBAClass, obj.JavaMessage.getColor);
            end
            color = obj.Cache.Color;
        end
        
        function set.Color(obj, color)
            %set.Color Set the value for property Color
            validateattributes(color, {obj.StdMsgsColorRGBAClass}, {'nonempty', 'scalar'}, 'ObjectColor', 'Color');
            
            obj.JavaMessage.setColor(color.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Color)
                obj.Cache.Color.setJavaObject(color.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Color = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Id = obj.Id;
            
            % Recursively copy compound properties
            cpObj.Color = copy(obj.Color);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Id = strObj.Id;
            obj.Color = feval([obj.StdMsgsColorRGBAClass '.loadobj'], strObj.Color);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Id = obj.Id;
            strObj.Color = saveobj(obj.Color);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.moveit_msgs.ObjectColor.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.moveit_msgs.ObjectColor;
            obj.reload(strObj);
        end
    end
end
