classdef OrientedBoundingBox < robotics.ros.Message
    %OrientedBoundingBox MATLAB implementation of moveit_msgs/OrientedBoundingBox
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'moveit_msgs/OrientedBoundingBox' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'da3bd98e7cb14efa4141367a9d886ee7' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        GeometryMsgsPoint32Class = robotics.ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/Point32') % Dispatch to MATLAB class for message type geometry_msgs/Point32
        GeometryMsgsPoseClass = robotics.ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/Pose') % Dispatch to MATLAB class for message type geometry_msgs/Pose
    end
    
    properties (Dependent)
        Pose
        Extents
    end
    
    properties (Access = protected)
        Cache = struct('Pose', [], 'Extents', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Extents', 'Pose'} % List of non-constant message properties
        ROSPropertyList = {'extents', 'pose'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = OrientedBoundingBox(msg)
            %OrientedBoundingBox Construct the message object OrientedBoundingBox
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function pose = get.Pose(obj)
            %get.Pose Get the value for property Pose
            if isempty(obj.Cache.Pose)
                obj.Cache.Pose = feval(obj.GeometryMsgsPoseClass, obj.JavaMessage.getPose);
            end
            pose = obj.Cache.Pose;
        end
        
        function set.Pose(obj, pose)
            %set.Pose Set the value for property Pose
            validateattributes(pose, {obj.GeometryMsgsPoseClass}, {'nonempty', 'scalar'}, 'OrientedBoundingBox', 'Pose');
            
            obj.JavaMessage.setPose(pose.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Pose)
                obj.Cache.Pose.setJavaObject(pose.getJavaObject);
            end
        end
        
        function extents = get.Extents(obj)
            %get.Extents Get the value for property Extents
            if isempty(obj.Cache.Extents)
                obj.Cache.Extents = feval(obj.GeometryMsgsPoint32Class, obj.JavaMessage.getExtents);
            end
            extents = obj.Cache.Extents;
        end
        
        function set.Extents(obj, extents)
            %set.Extents Set the value for property Extents
            validateattributes(extents, {obj.GeometryMsgsPoint32Class}, {'nonempty', 'scalar'}, 'OrientedBoundingBox', 'Extents');
            
            obj.JavaMessage.setExtents(extents.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Extents)
                obj.Cache.Extents.setJavaObject(extents.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Pose = [];
            obj.Cache.Extents = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Pose = copy(obj.Pose);
            cpObj.Extents = copy(obj.Extents);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Pose = feval([obj.GeometryMsgsPoseClass '.loadobj'], strObj.Pose);
            obj.Extents = feval([obj.GeometryMsgsPoint32Class '.loadobj'], strObj.Extents);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Pose = saveobj(obj.Pose);
            strObj.Extents = saveobj(obj.Extents);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.moveit_msgs.OrientedBoundingBox.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.moveit_msgs.OrientedBoundingBox;
            obj.reload(strObj);
        end
    end
end
