classdef PlannerInterfaceDescription < robotics.ros.Message
    %PlannerInterfaceDescription MATLAB implementation of moveit_msgs/PlannerInterfaceDescription
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'moveit_msgs/PlannerInterfaceDescription' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'ea5f6e6129aa1b110ccda9900d2bf25e' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Name
        PlannerIds
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Name', 'PlannerIds'} % List of non-constant message properties
        ROSPropertyList = {'name', 'planner_ids'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = PlannerInterfaceDescription(msg)
            %PlannerInterfaceDescription Construct the message object PlannerInterfaceDescription
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function name = get.Name(obj)
            %get.Name Get the value for property Name
            name = char(obj.JavaMessage.getName);
        end
        
        function set.Name(obj, name)
            %set.Name Set the value for property Name
            validateattributes(name, {'char'}, {}, 'PlannerInterfaceDescription', 'Name');
            
            obj.JavaMessage.setName(name);
        end
        
        function plannerids = get.PlannerIds(obj)
            %get.PlannerIds Get the value for property PlannerIds
            javaArray = obj.JavaMessage.getPlannerIds;
            array = obj.readJavaArray(javaArray, 'char');
            plannerids = arrayfun(@(x) char(x), array, 'UniformOutput', false);
        end
        
        function set.PlannerIds(obj, plannerids)
            %set.PlannerIds Set the value for property PlannerIds
            if ~isvector(plannerids) && isempty(plannerids)
                % Allow empty [] input
                plannerids = cell.empty(0,1);
            end
            
            validateattributes(plannerids, {'cell'}, {'vector'}, 'PlannerInterfaceDescription', 'PlannerIds');
            if any(cellfun(@(x) ~ischar(x), plannerids))
                error(message('robotics:ros:message:CellArrayStringError', ...
                    'plannerids'));
            end
            
            javaArray = obj.JavaMessage.getPlannerIds;
            array = obj.writeJavaArray(plannerids, javaArray, 'char');
            obj.JavaMessage.setPlannerIds(array);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Name = obj.Name;
            cpObj.PlannerIds = obj.PlannerIds;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Name = strObj.Name;
            obj.PlannerIds = strObj.PlannerIds;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Name = obj.Name;
            strObj.PlannerIds = obj.PlannerIds;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.moveit_msgs.PlannerInterfaceDescription.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.moveit_msgs.PlannerInterfaceDescription;
            obj.reload(strObj);
        end
    end
end
