classdef PlanningSceneComponents < robotics.ros.Message
    %PlanningSceneComponents MATLAB implementation of moveit_msgs/PlanningSceneComponents
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'moveit_msgs/PlanningSceneComponents' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'bc993e784476960b918b6e7ad5bb58ce' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant)
        SCENESETTINGS = uint32(1)
        ROBOTSTATE = uint32(2)
        ROBOTSTATEATTACHEDOBJECTS = uint32(4)
        WORLDOBJECTNAMES = uint32(8)
        WORLDOBJECTGEOMETRY = uint32(16)
        OCTOMAP = uint32(32)
        TRANSFORMS = uint32(64)
        ALLOWEDCOLLISIONMATRIX = uint32(128)
        LINKPADDINGANDSCALING = uint32(256)
        OBJECTCOLORS = uint32(512)
    end
    
    properties (Dependent)
        Components
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Components'} % List of non-constant message properties
        ROSPropertyList = {'components'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = PlanningSceneComponents(msg)
            %PlanningSceneComponents Construct the message object PlanningSceneComponents
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function components = get.Components(obj)
            %get.Components Get the value for property Components
            components = typecast(int32(obj.JavaMessage.getComponents), 'uint32');
        end
        
        function set.Components(obj, components)
            %set.Components Set the value for property Components
            validateattributes(components, {'numeric'}, {'nonempty', 'scalar'}, 'PlanningSceneComponents', 'Components');
            
            obj.JavaMessage.setComponents(components);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Components = obj.Components;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Components = strObj.Components;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Components = obj.Components;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.moveit_msgs.PlanningSceneComponents.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.moveit_msgs.PlanningSceneComponents;
            obj.reload(strObj);
        end
    end
end
