classdef RobotTrajectory < robotics.ros.Message
    %RobotTrajectory MATLAB implementation of moveit_msgs/RobotTrajectory
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'moveit_msgs/RobotTrajectory' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'dfa9556423d709a3729bcef664bddf67' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        TrajectoryMsgsJointTrajectoryClass = robotics.ros.msg.internal.MessageFactory.getClassForType('trajectory_msgs/JointTrajectory') % Dispatch to MATLAB class for message type trajectory_msgs/JointTrajectory
        TrajectoryMsgsMultiDOFJointTrajectoryClass = robotics.ros.msg.internal.MessageFactory.getClassForType('trajectory_msgs/MultiDOFJointTrajectory') % Dispatch to MATLAB class for message type trajectory_msgs/MultiDOFJointTrajectory
    end
    
    properties (Dependent)
        JointTrajectory
        MultiDofJointTrajectory
    end
    
    properties (Access = protected)
        Cache = struct('JointTrajectory', [], 'MultiDofJointTrajectory', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'JointTrajectory', 'MultiDofJointTrajectory'} % List of non-constant message properties
        ROSPropertyList = {'joint_trajectory', 'multi_dof_joint_trajectory'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = RobotTrajectory(msg)
            %RobotTrajectory Construct the message object RobotTrajectory
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function jointtrajectory = get.JointTrajectory(obj)
            %get.JointTrajectory Get the value for property JointTrajectory
            if isempty(obj.Cache.JointTrajectory)
                obj.Cache.JointTrajectory = feval(obj.TrajectoryMsgsJointTrajectoryClass, obj.JavaMessage.getJointTrajectory);
            end
            jointtrajectory = obj.Cache.JointTrajectory;
        end
        
        function set.JointTrajectory(obj, jointtrajectory)
            %set.JointTrajectory Set the value for property JointTrajectory
            validateattributes(jointtrajectory, {obj.TrajectoryMsgsJointTrajectoryClass}, {'nonempty', 'scalar'}, 'RobotTrajectory', 'JointTrajectory');
            
            obj.JavaMessage.setJointTrajectory(jointtrajectory.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.JointTrajectory)
                obj.Cache.JointTrajectory.setJavaObject(jointtrajectory.getJavaObject);
            end
        end
        
        function multidofjointtrajectory = get.MultiDofJointTrajectory(obj)
            %get.MultiDofJointTrajectory Get the value for property MultiDofJointTrajectory
            if isempty(obj.Cache.MultiDofJointTrajectory)
                obj.Cache.MultiDofJointTrajectory = feval(obj.TrajectoryMsgsMultiDOFJointTrajectoryClass, obj.JavaMessage.getMultiDofJointTrajectory);
            end
            multidofjointtrajectory = obj.Cache.MultiDofJointTrajectory;
        end
        
        function set.MultiDofJointTrajectory(obj, multidofjointtrajectory)
            %set.MultiDofJointTrajectory Set the value for property MultiDofJointTrajectory
            validateattributes(multidofjointtrajectory, {obj.TrajectoryMsgsMultiDOFJointTrajectoryClass}, {'nonempty', 'scalar'}, 'RobotTrajectory', 'MultiDofJointTrajectory');
            
            obj.JavaMessage.setMultiDofJointTrajectory(multidofjointtrajectory.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.MultiDofJointTrajectory)
                obj.Cache.MultiDofJointTrajectory.setJavaObject(multidofjointtrajectory.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.JointTrajectory = [];
            obj.Cache.MultiDofJointTrajectory = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.JointTrajectory = copy(obj.JointTrajectory);
            cpObj.MultiDofJointTrajectory = copy(obj.MultiDofJointTrajectory);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.JointTrajectory = feval([obj.TrajectoryMsgsJointTrajectoryClass '.loadobj'], strObj.JointTrajectory);
            obj.MultiDofJointTrajectory = feval([obj.TrajectoryMsgsMultiDOFJointTrajectoryClass '.loadobj'], strObj.MultiDofJointTrajectory);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.JointTrajectory = saveobj(obj.JointTrajectory);
            strObj.MultiDofJointTrajectory = saveobj(obj.MultiDofJointTrajectory);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.moveit_msgs.RobotTrajectory.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.moveit_msgs.RobotTrajectory;
            obj.reload(strObj);
        end
    end
end
