classdef SaveRobotStateToWarehouseRequest < robotics.ros.Message
    %SaveRobotStateToWarehouseRequest MATLAB implementation of moveit_msgs/SaveRobotStateToWarehouseRequest
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'moveit_msgs/SaveRobotStateToWarehouseRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '7937284880c511876f85988912ec5448' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        MoveitMsgsRobotStateClass = robotics.ros.msg.internal.MessageFactory.getClassForType('moveit_msgs/RobotState') % Dispatch to MATLAB class for message type moveit_msgs/RobotState
    end
    
    properties (Dependent)
        Name
        Robot
        State
    end
    
    properties (Access = protected)
        Cache = struct('State', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Name', 'Robot', 'State'} % List of non-constant message properties
        ROSPropertyList = {'name', 'robot', 'state'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = SaveRobotStateToWarehouseRequest(msg)
            %SaveRobotStateToWarehouseRequest Construct the message object SaveRobotStateToWarehouseRequest
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function name = get.Name(obj)
            %get.Name Get the value for property Name
            name = char(obj.JavaMessage.getName);
        end
        
        function set.Name(obj, name)
            %set.Name Set the value for property Name
            validateattributes(name, {'char'}, {}, 'SaveRobotStateToWarehouseRequest', 'Name');
            
            obj.JavaMessage.setName(name);
        end
        
        function robot = get.Robot(obj)
            %get.Robot Get the value for property Robot
            robot = char(obj.JavaMessage.getRobot);
        end
        
        function set.Robot(obj, robot)
            %set.Robot Set the value for property Robot
            validateattributes(robot, {'char'}, {}, 'SaveRobotStateToWarehouseRequest', 'Robot');
            
            obj.JavaMessage.setRobot(robot);
        end
        
        function state = get.State(obj)
            %get.State Get the value for property State
            if isempty(obj.Cache.State)
                obj.Cache.State = feval(obj.MoveitMsgsRobotStateClass, obj.JavaMessage.getState);
            end
            state = obj.Cache.State;
        end
        
        function set.State(obj, state)
            %set.State Set the value for property State
            validateattributes(state, {obj.MoveitMsgsRobotStateClass}, {'nonempty', 'scalar'}, 'SaveRobotStateToWarehouseRequest', 'State');
            
            obj.JavaMessage.setState(state.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.State)
                obj.Cache.State.setJavaObject(state.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.State = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Name = obj.Name;
            cpObj.Robot = obj.Robot;
            
            % Recursively copy compound properties
            cpObj.State = copy(obj.State);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Name = strObj.Name;
            obj.Robot = strObj.Robot;
            obj.State = feval([obj.MoveitMsgsRobotStateClass '.loadobj'], strObj.State);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Name = obj.Name;
            strObj.Robot = obj.Robot;
            strObj.State = saveobj(obj.State);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.moveit_msgs.SaveRobotStateToWarehouseRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.moveit_msgs.SaveRobotStateToWarehouseRequest;
            obj.reload(strObj);
        end
    end
end
