classdef WorkspaceParameters < robotics.ros.Message
    %WorkspaceParameters MATLAB implementation of moveit_msgs/WorkspaceParameters
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'moveit_msgs/WorkspaceParameters' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'd639a834e7b1f927e9f1d6c30e920016' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        GeometryMsgsVector3Class = robotics.ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/Vector3') % Dispatch to MATLAB class for message type geometry_msgs/Vector3
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        MinCorner
        MaxCorner
    end
    
    properties (Access = protected)
        Cache = struct('Header', [], 'MinCorner', [], 'MaxCorner', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Header', 'MaxCorner', 'MinCorner'} % List of non-constant message properties
        ROSPropertyList = {'header', 'max_corner', 'min_corner'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = WorkspaceParameters(msg)
            %WorkspaceParameters Construct the message object WorkspaceParameters
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'WorkspaceParameters', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function mincorner = get.MinCorner(obj)
            %get.MinCorner Get the value for property MinCorner
            if isempty(obj.Cache.MinCorner)
                obj.Cache.MinCorner = feval(obj.GeometryMsgsVector3Class, obj.JavaMessage.getMinCorner);
            end
            mincorner = obj.Cache.MinCorner;
        end
        
        function set.MinCorner(obj, mincorner)
            %set.MinCorner Set the value for property MinCorner
            validateattributes(mincorner, {obj.GeometryMsgsVector3Class}, {'nonempty', 'scalar'}, 'WorkspaceParameters', 'MinCorner');
            
            obj.JavaMessage.setMinCorner(mincorner.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.MinCorner)
                obj.Cache.MinCorner.setJavaObject(mincorner.getJavaObject);
            end
        end
        
        function maxcorner = get.MaxCorner(obj)
            %get.MaxCorner Get the value for property MaxCorner
            if isempty(obj.Cache.MaxCorner)
                obj.Cache.MaxCorner = feval(obj.GeometryMsgsVector3Class, obj.JavaMessage.getMaxCorner);
            end
            maxcorner = obj.Cache.MaxCorner;
        end
        
        function set.MaxCorner(obj, maxcorner)
            %set.MaxCorner Set the value for property MaxCorner
            validateattributes(maxcorner, {obj.GeometryMsgsVector3Class}, {'nonempty', 'scalar'}, 'WorkspaceParameters', 'MaxCorner');
            
            obj.JavaMessage.setMaxCorner(maxcorner.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.MaxCorner)
                obj.Cache.MaxCorner.setJavaObject(maxcorner.getJavaObject);
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
            obj.Cache.MinCorner = [];
            obj.Cache.MaxCorner = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
            cpObj.MinCorner = copy(obj.MinCorner);
            cpObj.MaxCorner = copy(obj.MaxCorner);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
            obj.MinCorner = feval([obj.GeometryMsgsVector3Class '.loadobj'], strObj.MinCorner);
            obj.MaxCorner = feval([obj.GeometryMsgsVector3Class '.loadobj'], strObj.MaxCorner);
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Header = saveobj(obj.Header);
            strObj.MinCorner = saveobj(obj.MinCorner);
            strObj.MaxCorner = saveobj(obj.MaxCorner);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.moveit_msgs.WorkspaceParameters.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.moveit_msgs.WorkspaceParameters;
            obj.reload(strObj);
        end
    end
end
