// Generated by gencpp from file ur10_cm/dual_arm_eff_msg.msg
// DO NOT EDIT!


#ifndef UR10_CM_MESSAGE_DUAL_ARM_EFF_MSG_H
#define UR10_CM_MESSAGE_DUAL_ARM_EFF_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace ur10_cm
{
template <class ContainerAllocator>
struct dual_arm_eff_msg_
{
  typedef dual_arm_eff_msg_<ContainerAllocator> Type;

  dual_arm_eff_msg_()
    : header()
    , hong_target_pose()
    , kong_target_pose()  {
    }
  dual_arm_eff_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , hong_target_pose(_alloc)
    , kong_target_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _hong_target_pose_type;
  _hong_target_pose_type hong_target_pose;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _kong_target_pose_type;
  _kong_target_pose_type kong_target_pose;




  typedef boost::shared_ptr< ::ur10_cm::dual_arm_eff_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur10_cm::dual_arm_eff_msg_<ContainerAllocator> const> ConstPtr;

}; // struct dual_arm_eff_msg_

typedef ::ur10_cm::dual_arm_eff_msg_<std::allocator<void> > dual_arm_eff_msg;

typedef boost::shared_ptr< ::ur10_cm::dual_arm_eff_msg > dual_arm_eff_msgPtr;
typedef boost::shared_ptr< ::ur10_cm::dual_arm_eff_msg const> dual_arm_eff_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur10_cm::dual_arm_eff_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur10_cm::dual_arm_eff_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ur10_cm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ur10_cm': ['/home/nazir/ws_moveit/src/ur10_cm/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ur10_cm::dual_arm_eff_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur10_cm::dual_arm_eff_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur10_cm::dual_arm_eff_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur10_cm::dual_arm_eff_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_cm::dual_arm_eff_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur10_cm::dual_arm_eff_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur10_cm::dual_arm_eff_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed9e1d286bd8f03ad213c307ed3832c4";
  }

  static const char* value(const ::ur10_cm::dual_arm_eff_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed9e1d286bd8f03aULL;
  static const uint64_t static_value2 = 0xd213c307ed3832c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::ur10_cm::dual_arm_eff_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur10_cm/dual_arm_eff_msg";
  }

  static const char* value(const ::ur10_cm::dual_arm_eff_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur10_cm::dual_arm_eff_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
geometry_msgs/Pose hong_target_pose\n\
geometry_msgs/Pose kong_target_pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::ur10_cm::dual_arm_eff_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur10_cm::dual_arm_eff_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.hong_target_pose);
      stream.next(m.kong_target_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dual_arm_eff_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur10_cm::dual_arm_eff_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ur10_cm::dual_arm_eff_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "hong_target_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.hong_target_pose);
    s << indent << "kong_target_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.kong_target_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UR10_CM_MESSAGE_DUAL_ARM_EFF_MSG_H
