function cm_accel = cm_acceleration(cm_velocity,q,dqdt,ddqdt)
                     
    syms q4(t) q5(t) q6(t) dqdt1(t) dqdt2(t) dqdt4(t) dqdt5(t) dqdt6(t)
    
    cm_vel_t = subs(cm_velocity,...
                    [q(4),q(5),q(6),...
                     dqdt(1),dqdt(2),dqdt(4),dqdt(5),dqdt(6)],...
                    [q4(t),q5(t),q6(t),...
                     dqdt1(t),dqdt2(t),dqdt4(t),dqdt5(t),dqdt6(t)]);
                        
    
    cm_accel_t = diff(cm_vel_t,t);
    
    
    cm_accel = subs(cm_accel_t,...
                   [q4(t),q5(t),q6(t),...
                    dqdt1(t),dqdt2(t),...
                    dqdt4(t),dqdt5(t),dqdt6(t),...
                    diff(q4(t), t),diff(q5(t), t),diff(q6(t), t),...
                    diff(dqdt1(t), t),diff(dqdt2(t), t),...
                    diff(dqdt4(t), t),diff(dqdt5(t), t),diff(dqdt6(t), t)],...
                   [q(4),q(5),q(6),...
                    dqdt(1),dqdt(2),...
                    dqdt(4),dqdt(5),dqdt(6),...
                    dqdt(4),dqdt(5),dqdt(6),...
                    ddqdt(1),ddqdt(2),...
                    ddqdt(4),ddqdt(5),ddqdt(6)]);
end